repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: '\.(astro|css|jsx?|tsx?)$'
        additional_dependencies:
          - prettier@2.8.0
