repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: '\.(astro|css|jsx?|tsx?)$'
        additional_dependencies:
          - prettier@3.0.0
          - prettier-plugin-astro@0.11.0
