baseURL = "https://www.jgosmann.de/"
languageCode = "en-us"
title = "Jan Gosmann"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT = true

[module]
  [[module.mounts]]
    source = "assets/fonts"
    target = "static/fonts"

  [[module.mounts]]
    source = "favicons"
    target = "static"

  [[module.mounts]]
    source = "lib"
    target = "static/js"

  [[module.mounts]]
    source = "static"
    target = "static"

[markup.goldmark.renderer]
unsafe = true
