baseURL = "https://www.jgosmann.de/"
languageCode = "en-us"
title = "Jan Gosmann"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT = true
DefaultContentLanguage = "en"

[languages.en]
weight = 1

[languages.de]
weight = 2

[module]
  [[module.mounts]]
    source = "node_modules/flag-icon-css/flags"
    target = "static/flags"

  [[module.mounts]]
    source = "assets/fonts"
    target = "static/fonts"

  [[module.mounts]]
    source = "favicons"
    target = "static"

  [[module.mounts]]
    source = "lib"
    target = "static/js"

  [[module.mounts]]
    source = "static"
    target = "static"

[markup.goldmark.renderer]
unsafe = true
